#!/bin/bash


if [ -z "$KNOWROB_WEB_PORT" ]
then
   export KNOWROB_WEB_PORT=5000
fi


# Check if mongo_db is running or stopped and start otherwise

RUNNING=$(docker inspect --format="{{ .State.Running }}" mongo_db 2>/dev/null)

if [ $? -eq 1 ]; then # container does not exist
  echo "No MongoDB container exists, creating a new one..."
  docker run -d -p 27017:27017 --volumes-from mongo_data --name mongo_db mongo
fi

if [ "$RUNNING" == 'false' ]; then # container exists, but stopped
  echo "MongoDB container exists, starting it..."
  docker start mongo_db
fi


# Check if nginx-proxy is running or stopped and start otherwise

RUNNING=$(docker inspect --format="{{ .State.Running }}" nginx-proxy 2>/dev/null)

if [ $? -eq 1 ]; then # container does not exist
  echo "No nginx-proxy container exists, creating a new one..."
  docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock --name nginx-proxy -t knowrob/nginx-proxy
fi

if [ "$RUNNING" == 'false' ]; then # container exists, but stopped
  echo "nginx-proxy container exists, starting it..."
  docker start nginx-proxy
fi


# Check if user_db container exists and create otherwise
RUNNING=$(docker inspect --format="{{ .State.Running }}" user_db 2>/dev/null)

if [ $? -eq 1 ]; then # container does not exist
  echo "No user DB container exists, creating a new one..."
  docker run -d -v /opt/webapp/db --name user_db knowrob/user_db true
fi


# start a knowrob container for the tutorials
RUNNING=$(docker inspect --format="{{ .State.Running }}" tutorials 2>/dev/null)

if [ $? -eq 1 ]; then # container does not exist
  echo "No tutorials container exists, creating a new one..."
  docker run -e VIRTUAL_HOST=tutorials -e VIRTUAL_PORT=9090 --volumes-from knowrob_data --link mongo_db:mongo --name tutorials -d knowrob/hydro-knowrob-daemon
fi

if [ "$RUNNING" == 'false' ]; then # container exists, but stopped
  echo "tutorials container exists, starting it..."
  docker start tutorials
fi


# start webrob container
RUNNING=$(docker inspect --format="{{ .State.Running }}" webrob 2>/dev/null)

if [ $? -eq 1 ]; then # container does not exist
  echo "No Web app container exists, creating a new one..."
  docker run --rm -i -p $KNOWROB_WEB_PORT:5000 --volumes-from user_db --volumes-from knowrob_data -e VIRTUAL_HOST=webrob -e VIRTUAL_PORT=5000 --name webrob -v /var/run/docker.sock:/var/run/docker.sock knowrob/webrob python webrob.py
fi

if [ "$RUNNING" == 'false' ]; then # container exists, but stopped
  echo "Web app container exists, starting it..."
  docker start webrob
fi
