#!/bin/bash
docker pull busybox
docker pull mongo
docker pull nginx
docker pull jwilder/docker-gen
docker pull openease/dns
docker pull knowrob/user_db
docker pull knowrob/user_data
docker pull knowrob/postgres

# Application container
docker pull knowrob/hydro-knowrob-daemon
docker pull knowrob/dockerbridge


# WebApp container
docker pull openease/flask

