drop table if exists docu;
create table docu (
    id serial primary key,
    key text not null,
    text text not null
);

INSERT INTO Docu VALUES(0, 'WELCOME', '<h1 class="content-box-header">Welcome to openEASE</h1>openEASE is a web-based knowledge service providing robot and human activity data. It contains semantically annotated data of manipulation actions, including the environment the agent is acting in, the objects it manipulates, the task it performs, and the behavior it generates. The episode representations can include images captured by the robot, other sensor datastreams as well as full-body poses. A powerful query language and inference tools, allow reasoning about the data and retrieving requested information based on semantic queries. Based on the data and using the inference tools robots can answer queries regarding to what they did, why, how, what happened, and what they saw.');

INSERT INTO Docu VALUES(1, 'OVERVIEW', '<h1 class="content-box-header">Welcome to openEASE</h1>You successfully logged into openEASE!<br><br>Through this web interface, we provide access to comprehensive episodic memory of bleeding edge autonomous robotic experiments performed in realistic environments. The episodic memory is represented based on predicate logics using the programming language <a href="http://www.swi-prolog.org/">Prolog</a>. Please consider stepping through the <a href="knowrob/tutorials">query language tutorials</a> and watching the <a href="http://www.youtube-nocookie.com/embed/iu_Y7mxDjgA">tutorial video</a> linked at the bottom of this page before investigating one of the experiments.<br><br> The experiments are ordered according to their corresponding research projects. To access the experiments, please click on the <a href="knowrob">Knowledge Base</a> menu entry at the top left of this page or select one of the experiments directly from the menu at the top right of this page. This will redirect you to the <a href="knowrob">main user interface</a> of openEASE.');